### PR TITLE
integrate development environment

### PR DESCRIPTION
**Pull request by RealFakeAccount**
An attempt to solve issue #15

### CODE REVIEW

**Comment by bbrianh** [comment]
Could you move the idea folder and gradle related files to the root instead of inside src?

**Comment by RealFakeAccount** [comment]
> Could you move the idea folder and gradle related files to the root instead of inside src?

ACK. working on it.

**Comment by RealFakeAccount** [comment]
> Could you move the idea folder and gradle related files to the root instead of inside src?

See the new commit. I've merged gitignore. `description.html` is not applicable anymore, so it's deleted. Other XMLs have been generated by android studio, so they are deleted as well.

**Comment by bbrianh** [comment]
Can't build the project. Error with androidx packages do not exist
image

**Comment by RealFakeAccount** [comment]
> 

Open the util folder in IDEA

**Comment by RealFakeAccount** [comment]
> Can't build the project. Error with androidx packages do not exist image

Open util in IDEA

**Comment by MakoStrwlkr** [comment]
Okay, so would simply pulling from this pr be enough to fix the issues locally? (I have already installed the necessary environments.) Or is there anything else that we must do to make sure it works on our machines too, when going from the previous version to this one?

**Comment by RealFakeAccount** [comment]
> Okay, so would simply pulling from this pr be enough to fix the issues locally? (I have already installed the necessary environments.) Or is there anything else that we must do to make sure it works on our machines too, when going from the previous version to this one?

I think if you open `./course-project-uwutever/RegexApp/app/src/main/java/com/uwutever/RegexApp/utils/` as root folder in IDEA, it will be the same as before. Would you mind testing it for me?

**Comment by bbrianh** [comment]
Is it possible to create a separate module for the backend so that we could test individually?

**Pull request merged**
